version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.16.3

    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Setup NPM Token
          command: |
              yarn config set registry "https://registry.npmjs.org/"
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
              echo "registry=https://registry.npmjs.org/" >> .npmrc

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: lint
          command: ./run lint
      - run:
          name: check types
          command: ./run types
      - run:
          name: test
          command: ./run coverage
      - run:
          name: build
          command: ./run build
      - run:
          name: release
          command: yarn run semantic-release
